### ISSUE TITLE
Example run code needs to be updated

### ISSUE THREAD

**Issue by JadenTravnik** [korymath/gym-multiplot#4]
When I run the code on the README:

```
from multiplot import *
graphOut = mp('runs')
```

while in the given directory I get:
  File "path_to_multiplot/multiplot/multiplot.py", line 61, in mp
    directory = args.directory
AttributeError: 'str' object has no attribute 'directory'

It seems like config information needs to be passed in, namely:

- directory
- buckets
- group
- figSizeX
- figSizeY
- rewardTitle
- lengthTitile
- plotMean
- plotStd

but it isn't clear what types all of these variables should be or what defaults could be used for the example data.

**Comment by JadenTravnik** [comment]
Running with 
```
python multiplot.py -d CartPole-v0/ -g True
```
gives

AttributeError: 'AxesSubplot' object has no attribute 'set_prop_cycle

**Comment by korymath** [comment]
Make sure that you have cycler installed. 

~~~
pip install cycler
~~~

Updated the run code.

**Comment by korymath** [comment]
Also, calling the help on the python script should help with defaults.
